### ISSUE TITLE
Type of hooking

### ISSUE THREAD

**Issue by grillenfrige** [alxbrn/r6s-external-nuklear-hook#5]
Wouldn't this type of hooking be easily detected since there are only so many syscalls like Nt.. couldn't they just store the signature of the function and compare it to what it should? Or am I think to much of Battle eye ?

**Comment by appleman1232** [comment]
So whats alternatives you can do @ here?

**Comment by qazxsw1597532018** [comment]
it is undetected if you do some changes of course.

**Comment by d3d11** [comment]
You're almost correct. Storing the signature of the function wouldn't work. There are thousands of hook-able functions and many Windows versions where they might have changed. Instead of storing the function signatures an AC would read them from the file on disk and compare to memory. This would be the ideal solution and it's only safe to assume they already do this.

There are many alternatives. As far as I know, BE does not do the solution I mentioned above at the moment, so finding another function would suffice. Aside from any potential detections, hooking kernel functions is probably the superior way to achieve kernel communication as there is very little overhead in syscalls and registers are obviously preserved.

If you're planning on using a similar hook, here are some tips:
- stay away from hooking common functions (functions hooked in open-source projects)
- stay away from function tables containing commonly hooked functions
- don't make the assumption that some function is unused. Don't trash any registers for your hook and make sure to return to normal execution after your handler is called.
- use MmProbeAndLockPages, MmMapLockedPagesSpecifyCache and MmProtectMdlSystemAddress with PAGE_EXECUTE_READWRITE like in https://github.com/alxbrn/r6s-external-nuklear-hook/blob/master/kernelmode/memory.h#L75 to write to the function safely.
